/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 baked_shirt_turquoise.glb --transform 
Files: baked_shirt_turquoise.glb [9.6MB] > C:\Users\damia\Desktop\mount_la\public\baked_shirt_turquoise-transformed.glb [687.13KB] (93%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BakedTurqTee(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/baked_shirt_turquoise-transformed.glb",
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          // negative y-position push the mesh towards the "main" section
          // DO NOT comment out any properties or else the mesh won't render
          name="Tshirt_A-Pose"
          geometry={nodes["Tshirt_A-Pose"].geometry}
          material={materials.Mockup_Material}
          position={[0, -0.5, 0]}
          // position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          // scale={4}
          scale={2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/baked_shirt_turquoise-transformed.glb");
